#! /bin/sh

ssh-keygen -t rsa -b 4096 -C "default" -f $HOME/.ssh/$1


# if $HOME/.ssh/backup not exists
# mkdir $HOME/.ssh/backup

# if $HOME/.ssh/config exists
cp $HOME/.ssh/config $HOME/.ssh/backup/config_backup

cat << EOS >> $HOME/.ssh/config

Host $1
  Port 22
  HostName github.com
  IdentityFile ~/.ssh/$1
  TCPKeepAlive yes
  IdentitiesOnly yes
EOS
